services:
  - type: web
    name: mochi-bot-backend
    runtime: python
    plan: starter  # Change to the desired paid plan
    region: frankfurt  # Choose your preferred region
    rootDir: mochi_bot_backend  # Specify the subfolder containing the backend
    buildCommand: |
      pip install -r requirements.txt
      npm install --prefix ../mochi_bot_frontend && npm run build --prefix ../mochi_bot_frontend
      mkdir -p staticfiles
      cp -r ../mochi_bot_frontend/build/* staticfiles/
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: cd mochi_bot_backend && gunicorn mochi_bot_backend.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mochi_bot_backend.settings
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: false  # Set to true if you want to enable debug mode, usually false in production
      - key: DJANGO_ALLOWED_HOSTS
        value: .render.com
      - key: DATABASE_URL
        fromDatabase:
          name: mochi-bot-db
          property: connectionString

databases:
  - name: mochi-bot-db
    postgresMajorVersion: "16"  # Specify the PostgreSQL version
    region: frankfurt  # Specify the deployment region
    plan: starter  # Specify the desired plan
    databaseName: mochi_bot_db  # Specify the database name
    user: mochi_user  # Specify the database user
    ipAllowList:  # Define IP allow list
      - source: 203.0.113.4/30
        description: office
      - source: 198.51.100.1
        description: home

envVarGroups:
  - name: my-env-group
    envVars:
      - key: API_BASE_URL
        value: https://api.example.com
      - key: APP_SECRET
        generateValue: true
      - key: STRIPE_API_KEY
        sync: false